export const mockProducts = [
  {
    id: 1,
    nameEn: "Fresh Organic Apple",
    nameAr: "تفاح عضوي طازج",
    price: 45000,
    oldPrice: 50000,
    weightEn: "1 Ton",
    weightAr: "1 طن",
    image: "/images/product-apple-main.jpg",
    badgeEn: "New",
    badgeAr: "جديد",
    rating: 4,
    reviews: 12,
    badgeColor: "bg-flash",
    images: [
      "/images/product-apple-main.jpg",
      "/images/product-apple-1.jpg",
      "/images/product-apple-2.jpg"
    ],
    descriptionEn: "Experience the crisp, juicy goodness of our farm-fresh organic apples. Hand-picked at peak ripeness to ensure maximum flavor and nutrition. Perfect for snacking, baking, or adding to your favorite salads.",
    descriptionAr: "استمتع بطعم التفاح العضوي الطازج والمقرمش المقطوف بعناية لضمان أقصى قدر من النكهة. مثالي كوجبة خفيفة صحية أو إضافته للسلطات.",
    originEn: "Imported from Italy",
    originAr: "مستورد من إيطاليا",
    storageEn: "Store in a cool, dry place. Refrigerate after opening.",
    storageAr: "يُحفظ في مكان بارد وجاف. يُبرد بعد الفتح.",
    shelfLifeEn: "Up to 2 weeks when refrigerated",
    shelfLifeAr: "حتى أسبوعين عند التبريد",
    nutritionEn: "Rich in Fiber, Vitamin C, and Antioxidants",
    nutritionAr: "غني بالألياف وفيتامين سي ومضادات الأكسدة",
    usageEn: "Perfect for fresh consumption, juicing, baking, and salads",
    usageAr: "مثالي للاستهلاك الطازج والعصائر والخبز والسلطات",
  },
  {
    id: 2,
    nameEn: "Premium Strawberries",
    nameAr: "فراولة ممتازة",
    price: 65000,
    oldPrice: 75000,
    weightEn: "1 Ton",
    weightAr: "1 طن",
    image: "/images/product-strawberry-main.jpg",
    badgeEn: "On Sale",
    badgeAr: "تخفيض",
    rating: 5,
    reviews: 24,
    badgeColor: "bg-primary",
    images: [
      "/images/product-strawberry-main.jpg",
      "/images/product-strawberry-1.jpg"
    ],
    descriptionEn: "Sweet, juicy strawberries sourced from organic farms. Packed with vitamin C, antioxidants, and pure flavor.",
    descriptionAr: "فراولة حلوة ومليئة بالعصارة من المزارع العضوية. غنية بفيتامين سي ومضادات الأكسدة والنكهة النقية.",
    originEn: "Locally sourced from Egyptian farms",
    originAr: "من المزارع المصرية المحلية",
    storageEn: "Store in a cool place. Best consumed within 3 days.",
    storageAr: "يُحفظ في مكان بارد. يُفضل استهلاكه خلال 3 أيام.",
    shelfLifeEn: "3-5 days when refrigerated",
    shelfLifeAr: "3-5 أيام عند التبريد",
    nutritionEn: "Rich in Vitamin C, Manganese, and Folate",
    nutritionAr: "غني بفيتامين سي والمنغنيز وحمض الفوليك",
    usageEn: "Great for desserts, smoothies, jams, and fresh eating",
    usageAr: "مثالي للحلويات والعصائر والمربى والأكل الطازج",
  },
  {
    id: 3,
    nameEn: "Organic Bananas",
    nameAr: "موز عضوي",
    price: 25000,
    oldPrice: null,
    weightEn: "1 Ton",
    weightAr: "1 طن",
    image: "/images/product-banana-main.jpg",
    badgeEn: "Top Rated",
    badgeAr: "الأكثر تقييمًا",
    rating: 4,
    reviews: 89,
    badgeColor: "bg-cta",
    images: [
      "/images/product-banana-main.jpg",
      "/images/product-banana-1.jpg"
    ],
    descriptionEn: "Energize your day with our premium organic bananas. Rich in potassium, naturally sweet, and perfect for smoothies or on-the-go snacks.",
    descriptionAr: "ابدأ يومك بنشاط مع الموز العضوي الممتاز. غني بالبوتاسيوم وحلو المذاق بشكل طبيعي، ومثالي للعصائر أو الوجبات الخفيفة.",
    originEn: "Imported from Ecuador",
    originAr: "مستورد من الإكوادور",
    storageEn: "Store at room temperature. Refrigerate when ripe.",
    storageAr: "يُحفظ في درجة حرارة الغرفة. يُبرد عند النضج.",
    shelfLifeEn: "5-7 days at room temperature",
    shelfLifeAr: "5-7 أيام في حرارة الغرفة",
    nutritionEn: "Rich in Potassium, Vitamin B6, and Fiber",
    nutritionAr: "غني بالبوتاسيوم وفيتامين ب6 والألياف",
    usageEn: "Perfect for smoothies, baking, cereal topping, and snacking",
    usageAr: "مثالي للعصائر والخبز وإضافته للحبوب والوجبات الخفيفة",
  },
  {
    id: 4,
    nameEn: "Fresh Avocados",
    nameAr: "أفوكادو طازج",
    price: 120000,
    oldPrice: null,
    weightEn: "1 Ton",
    weightAr: "1 طن",
    image: "/images/product-avocado-main.jpg",
    badgeEn: "Best Seller",
    badgeAr: "الأكثر مبيعًا",
    rating: 5,
    reviews: 45,
    badgeColor: "bg-primary-dark",
    images: [
      "/images/product-avocado-main.jpg",
      "/images/product-avocado-1.jpg"
    ],
    descriptionEn: "Creamy, nutrient-dense avocados perfect for guilt-free toasts, salads, and dips. High in healthy fats.",
    descriptionAr: "أفوكادو كريمي غني بالعناصر الغذائية مثالي للتوست والسلطات والصلصات. يحتوي على نسبة عالية من الدهون الصحية.",
    originEn: "Imported from Mexico",
    originAr: "مستورد من المكسيك",
    storageEn: "Store at room temperature until ripe, then refrigerate.",
    storageAr: "يُحفظ في حرارة الغرفة حتى النضج، ثم يُبرد.",
    shelfLifeEn: "4-5 days when ripe and refrigerated",
    shelfLifeAr: "4-5 أيام عند النضج والتبريد",
    nutritionEn: "Rich in Healthy Fats, Potassium, and Vitamin K",
    nutritionAr: "غني بالدهون الصحية والبوتاسيوم وفيتامين ك",
    usageEn: "Ideal for guacamole, salads, toast, and smoothies",
    usageAr: "مثالي للجواكامولي والسلطات والتوست والعصائر",
  },
  {
    id: 5,
    nameEn: "Green Grapes",
    nameAr: "عنب أخضر",
    price: 55000,
    oldPrice: 70000,
    weightEn: "1 Ton",
    weightAr: "1 طن",
    image: "/images/product-grape-main1.jpg",
    badgeEn: "Popular",
    badgeAr: "شائع",
    rating: 4,
    reviews: 32,
    badgeColor: "bg-primary",
    images: [
      "/images/product-grape-main1.jpg"
    ],
    descriptionEn: "Crisp, sweet seedless green grapes perfect for quick snacking and fruit platters.",
    descriptionAr: "عنب أخضر بدون بذور، مقرمش وحلو المذاق، مثالي للوجبات الخفيفة السريعة وأطباق الفاكهة.",
    originEn: "Locally sourced from Upper Egypt",
    originAr: "من مزارع صعيد مصر",
    storageEn: "Refrigerate and consume within a week.",
    storageAr: "يُبرد ويُستهلك خلال أسبوع.",
    shelfLifeEn: "Up to 1 week when refrigerated",
    shelfLifeAr: "حتى أسبوع عند التبريد",
    nutritionEn: "Rich in Vitamins C & K, and Antioxidants",
    nutritionAr: "غني بفيتامين سي و ك ومضادات الأكسدة",
    usageEn: "Perfect for snacking, fruit salads, and juice",
    usageAr: "مثالي للوجبات الخفيفة وسلطة الفواكه والعصير",
  },
  {
    id: 6,
    nameEn: "Juicy Oranges",
    nameAr: "برتقال طازج",
    price: 18000,
    oldPrice: 22000,
    weightEn: "1 Ton",
    weightAr: "1 طن",
    image: "/images/product-orange-main.jpg",
    badgeEn: "New",
    badgeAr: "جديد",
    rating: 5,
    reviews: 112,
    badgeColor: "bg-flash",
    images: [
      "/images/product-orange-main.jpg",
      "/images/product-orange-1.jpg"
    ],
    descriptionEn: "Experience the ultimate burst of vitamin C with our fresh, sweet, and juicy oranges. Ideal for juicing or peeling.",
    descriptionAr: "استمتع بأقصى جرعة من فيتامين سي مع البرتقال الطازج والحلو والمليء بالعصارة. مثالي للعصر أو التناول المباشر.",
    originEn: "From the finest farms in Fayoum, Egypt",
    originAr: "من أفضل مزارع الفيوم، مصر",
    storageEn: "Store in a cool, dry place or refrigerate.",
    storageAr: "يُحفظ في مكان بارد وجاف أو يُبرد.",
    shelfLifeEn: "Up to 2 weeks when refrigerated",
    shelfLifeAr: "حتى أسبوعين عند التبريد",
    nutritionEn: "Excellent source of Vitamin C and Fiber",
    nutritionAr: "مصدر ممتاز لفيتامين سي والألياف",
    usageEn: "Great for juicing, eating fresh, and cooking",
    usageAr: "مثالي للعصر والأكل الطازج والطبخ",
  },
  {
    id: 7,
    nameEn: "Fresh Blueberries",
    nameAr: "توت أزرق طازج",
    price: 250000,
    oldPrice: 280000,
    weightEn: "1 Ton",
    weightAr: "1 طن",
    image: "/images/product-blueberry-main.jpg",
    badgeEn: "Limited",
    badgeAr: "كمية محدودة",
    rating: 4,
    reviews: 67,
    badgeColor: "bg-text-main",
    images: [
      "/images/product-blueberry-main.jpg"
    ],
    descriptionEn: "Plump, sweet, and antioxidant-rich blueberries. Hand-harvested for the finest quality.",
    descriptionAr: "توت أزرق ممتلئ وحلو وغني بمضادات الأكسدة. تم حصاده يدوياً لضمان أفضل جودة.",
    originEn: "Imported from Chile",
    originAr: "مستورد من تشيلي",
    storageEn: "Refrigerate immediately. Do not wash until ready to eat.",
    storageAr: "يُبرد فوراً. لا تُغسل حتى وقت الاستهلاك.",
    shelfLifeEn: "Up to 10 days when refrigerated",
    shelfLifeAr: "حتى 10 أيام عند التبريد",
    nutritionEn: "Superfood: Rich in Antioxidants, Vitamin C & K",
    nutritionAr: "سوبر فود: غني بمضادات الأكسدة وفيتامين سي و ك",
    usageEn: "Great for smoothies, oatmeal, baking, and snacking",
    usageAr: "مثالي للعصائر والشوفان والخبز والوجبات الخفيفة",
  },
  {
    id: 8,
    nameEn: "Ripe Mango",
    nameAr: "مانجو ناضج",
    price: 75000,
    oldPrice: 95000,
    weightEn: "1 Ton",
    weightAr: "1 طن",
    image: "/images/product-mango-main1.jpg",
    badgeEn: "Seasonal",
    badgeAr: "موسمي",
    rating: 5,
    reviews: 215,
    badgeColor: "bg-cta",
    images: [
      "/images/product-mango-main1.jpg"
    ],
    descriptionEn: "Golden, tropical, melt-in-your-mouth sweet mangoes. Perfect for desserts and direct snacking.",
    descriptionAr: "مانجو استوائية ذهبية تذوب في الفم بحلاوتها. مثالية للحلويات أو تناولها كما هي.",
    originEn: "Locally sourced from Ismailia, Egypt",
    originAr: "من مزارع الإسماعيلية، مصر",
    storageEn: "Ripen at room temperature, then refrigerate.",
    storageAr: "يُنضج في حرارة الغرفة، ثم يُبرد.",
    shelfLifeEn: "5-7 days when ripe and refrigerated",
    shelfLifeAr: "5-7 أيام عند النضج والتبريد",
    nutritionEn: "Rich in Vitamin A, C, and Dietary Fiber",
    nutritionAr: "غني بفيتامين أ و سي والألياف الغذائية",
    usageEn: "Perfect for smoothies, desserts, salads, and fresh eating",
    usageAr: "مثالي للعصائر والحلويات والسلطات والأكل الطازج",
  }
];
